export const claimAirdropAbi = [
  {
    type: 'constructor',
    inputs: [
      { name: '_addressResolver', type: 'address', internalType: 'address' },
      { name: 'deployerContract_', type: 'address', internalType: 'address' },
      {
        name: 'feesData_',
        type: 'tuple',
        internalType: 'struct FeesData',
        components: [
          { name: 'feePoolChain', type: 'uint32', internalType: 'uint32' },
          { name: 'feePoolToken', type: 'address', internalType: 'address' },
          { name: 'maxFees', type: 'uint256', internalType: 'uint256' },
        ],
      },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'addAirdropReceivers',
    inputs: [
      { name: 'receivers_', type: 'address[]', internalType: 'address[]' },
      { name: 'amounts_', type: 'uint256[]', internalType: 'uint256[]' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'addressResolver',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IAddressResolver' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'airdropReceivers',
    inputs: [{ name: '', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'allContractsDeployed',
    inputs: [{ name: 'chainSlug_', type: 'uint32', internalType: 'uint32' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'auctionHouse',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IAuctionHouse' }],
    stateMutability: 'view',
  },
  { type: 'function', name: 'cancelOwnershipHandover', inputs: [], outputs: [], stateMutability: 'payable' },
  {
    type: 'function',
    name: 'claimAirdrop',
    inputs: [{ name: '_instance', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'completeOwnershipHandover',
    inputs: [{ name: 'pendingOwner', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'feesData',
    inputs: [],
    outputs: [
      { name: 'feePoolChain', type: 'uint32', internalType: 'uint32' },
      { name: 'feePoolToken', type: 'address', internalType: 'address' },
      { name: 'maxFees', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getFeesData',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct FeesData',
        components: [
          { name: 'feePoolChain', type: 'uint32', internalType: 'uint32' },
          { name: 'feePoolToken', type: 'address', internalType: 'address' },
          { name: 'maxFees', type: 'uint256', internalType: 'uint256' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'isReadCall',
    inputs: [],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'isValidPromise',
    inputs: [{ name: '', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [{ name: 'result', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'ownershipHandoverExpiresAt',
    inputs: [{ name: 'pendingOwner', type: 'address', internalType: 'address' }],
    outputs: [{ name: 'result', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  { type: 'function', name: 'renounceOwnership', inputs: [], outputs: [], stateMutability: 'payable' },
  { type: 'function', name: 'requestOwnershipHandover', inputs: [], outputs: [], stateMutability: 'payable' },
  {
    type: 'function',
    name: 'transferOwnership',
    inputs: [{ name: 'newOwner', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'watcherPrecompile',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IWatcherPrecompile' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'OwnershipHandoverCanceled',
    inputs: [{ name: 'pendingOwner', type: 'address', indexed: true, internalType: 'address' }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OwnershipHandoverRequested',
    inputs: [{ name: 'pendingOwner', type: 'address', indexed: true, internalType: 'address' }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OwnershipTransferred',
    inputs: [
      { name: 'oldOwner', type: 'address', indexed: true, internalType: 'address' },
      { name: 'newOwner', type: 'address', indexed: true, internalType: 'address' },
    ],
    anonymous: false,
  },
  { type: 'error', name: 'AlreadyInitialized', inputs: [] },
  { type: 'error', name: 'FeesDataNotSet', inputs: [] },
  { type: 'error', name: 'InvalidPromise', inputs: [] },
  { type: 'error', name: 'NewOwnerIsZeroAddress', inputs: [] },
  { type: 'error', name: 'NoHandoverRequest', inputs: [] },
  { type: 'error', name: 'Unauthorized', inputs: [] },
] as const
